config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "static_pages#home"
  get '/404', to: 'errors#not_found'
  get  "/about", to: "static_pages#about"
  get  "/help", to: "static_pages#help"
  get  "/user-management", to: "static_pages#user_management"
  get  "/search", to: "static_pages#search"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  devise_scope :user do
    delete "delete_avatar" => "registrations"
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :site_settings, only: [:edit, :update], :path => "settings" do
    member do
      delete :delete_default_avatar
      delete :delete_logo
      delete :delete_favicon
      delete :delete_apple_touch_icon
    end
  end
  resources :help_sections, only: [:new, :create, :edit, :update, :destroy], :path => "documentation"
  resources :support_issues, only: [:index, :show, :new, :create, :update], :path => "support" do
    resources :support_replies, only: [:create], :path => "reply"
    resources :support_comments, only: [:create], :path => "comment"
    resources :support_notes, only: [:create], :path => "note"
  end
  resources :chats, only: [:create, :index] do
    resources :messages, only: [:create]
    collection do
      post :update_index
      get '/join_user_chat/:user_id/', to: 'chats#join_user_chat', :as => :join_user_chat
      get '/join_group_chat/:group_id/', to: 'chats#join_group_chat', :as => :join_group_chat
      get :search
    end
    member do
      post :update_show
      post :pin
      post :unpin
      post :hide
      post :clear_unread_messages
      post :load_more_messages
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :tables, only: [:show, :create, :update]
  get '/edit_collaborations/:record_id/:record_type', to: 'collaborations#edit_collaborations', :as => :edit_collaborations
  get '/:type/:record_id/collaboration_logs', type: /(calendars|decks|notes)/, to: 'collaborations#collaboration_logs', :as => :collaboration_logs
  patch '/change_owner/:record_id/:record_type', to: 'collaborations#change_owner', :as => :change_owner
  patch '/add_collaborator/:record_id/:record_type', to: 'collaborations#add_collaborator', :as => :add_collaborator
  patch '/remove_collaborator/:record_id/:record_type', to: 'collaborations#remove_collaborator', :as => :remove_collaborator
  patch '/add_group/:record_id/:record_type', to: 'collaborations#add_group', :as => :add_group
  patch '/remove_group/:record_id/:record_type', to: 'collaborations#remove_group', :as => :remove_group
  resources :tags, only: [:show] do
    collection do
      get '/edit_item_list/:record_id/:record_type', to: 'tags#edit_item_list', :as => :edit_item_list
      patch '/add/:record_id/:record_type', to: 'tags#add', :as => :add
      patch '/remove/:record_id/:record_type', to: 'tags#remove', :as => :remove
      get '/get_id/:tag_name', to: 'tags#get_id', :as => :get_id
      get :search
    end
  end
  resources :stars, only: []  do
    collection do
      patch '/add/:record_id/:record_type', to: 'stars#add', :as => :add
      patch '/remove/:record_id/:record_type', to: 'stars#remove', :as => :remove
    end
  end
  get '/:type/:record_id/stargazers', type: /(calendars|decks|notes)/, to: 'stars#stargazers', :as => :stargazers
  resources :calendars do
    resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :recurring_events, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :recurring_events do
      patch :add_exception
    end
    get :by_day
    post :update_events_for_tz
  end
  get '/calendar', to: 'calendars#user_calendar', :as => :user_calendar
  get '/calendar/by_day', to: 'calendars#user_calendar_by_day', :as => :user_calendar_by_day
  resources :decks do
    resources :cards do
      patch '/update_position/:display_position', to: 'cards#update_position', :as => :update_position
    end
    post :shuffle
  end
  resources :notes
  resources :groups do
    collection do
      get '/get_id/:group_name', to: 'groups#get_id', :as => :get_id
      get :search
    end
    patch :change_owner
    patch :add_member
    patch :remove_member
    get :edit_members
    get :show_members, :path => "members"
    get ':type', type: /(calendars|decks|notes)/, action: 'show_items', :as => :show_items
    get :membership_logs
    delete :delete_avatar
  end
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    collection do
      get '/get_id/:username', to: 'users#get_id', :as => :get_id
      get :search
    end
    member do
      delete :delete_avatar
      resources :support_issues, only: [:index], :path => "support"
      get :following
      get :followers
      get :show_groups, :path => "groups"
      get :show_stars, :path => "stars"
      get ':type', type: /(calendars|decks|notes)/, action: 'show_items', :as => :show_items
      get :bulk_edit_ownership
      post :bulk_transfer_ownership
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:help, :user_management]
  before_action :admin_user, only: [:user_management]

  def home
    item_types = ['calendars','decks','notes']
    if current_user
      @items = SiteSearch.search(
        page: params[:page],
        per_page: 12,
        admin: current_user.admin?,
        user_id: current_user.id,
        item_types: item_types
      )
    else
      @items = SiteSearch.search(
        page: params[:page],
        per_page: 12,
        item_types: item_types
      )
    end
  end

  def about; end

  def help
    @help_sections = HelpSection.all
  end

  def user_management
    if params[:view_admins].present? && params[:view_admins] == '1'
      @users = User.admin_search(params[:search], admin: true, page: params[:page], per_page: 2)
    else
      @users = User.admin_search(params[:search], page: params[:page], per_page: 2)
    end
  end

  def search
    if current_user
      @items = SiteSearch.query(
        params[:query],
        page: params[:page],
        per_page: 12,
        admin: current_user.admin?,
        user_id: current_user.id,
        item_types: params[:item_types],
        my_items: params[:my_items].present?,
        my_owned: params[:my_owned].present?,
        my_stars: params[:my_stars].present?
      )
    else
      @items = SiteSearch.query(
        params[:query],
        page: params[:page],
        per_page: 12,
        item_types: params[:item_types]
      )
    end
    @tags = @items.select { |item| item.respond_to?(:tags) && item.tags.present? }
              .flat_map(&:tags)
              .uniq
              .sort_by(&:last_activity_at)
              .reverse
    @start_result = ((@items.current_page - 1) * @items.per_page) + 1
    @end_result = [@items.current_page * @items.per_page, @items.total_entries].min
  end

  private

    def admin_user
      redirect_to root_path, alert: 'Not authorized.' unless current_user.admin?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
.container-xxl.g-0
  %h1 Help
  %div{:class => "card #{card_class}"}
    .card-body
      .row
        .col-md-3
          - if !@help_sections.empty? || SiteSetting.allow_users_to_contact_admins?
            %ul.list-group.list-group-flush.mb-3
              - @help_sections.each do |help_section|
                = link_to help_path(:anchor => 'help_section_' + help_section.id.to_s ), class: "text-break" do
                  %li{:class => "list-group-item list-group-item-action#{list_group_item_class}"}
                    = help_section.title
              - if SiteSetting.allow_users_to_contact_admins?
                = link_to help_path(:anchor => 'contact_admins') do
                  %li{:class => "list-group-item list-group-item-action#{list_group_item_class}"}
                    %i.bi.bi-envelope>
                    Contact Site Admins
          - if current_user.admin
            .mb-5
              = link_to new_help_section_path, class: link_class do
                %i.bi.bi-plus>
                Add help section
        .col-md-9
          - @help_sections.each do |help_section|
            = render help_section
          - if SiteSetting.allow_users_to_contact_admins?
            #contact_admins.mb-5
              %h2 Contact Site Admins
              %p Not finding what you need?
              .mb-3
                = link_to "Get Support", new_support_issue_path, class: "btn btn-primary btn-sm"
          - if current_user.admin && !@help_sections.empty?
            .mb-3
              = link_to new_help_section_path, class: link_class do
                %i.bi.bi-plus>
                Add help section

app/views/static_pages/home.html.haml
#home_content.row.grid
  - @items.each do |item|
    .col-sm-6.col-lg-4.col-xxl-3.mb-4.grid-item
      = render item.card_template_path, item: item
= will_paginate @items, list_classes: %w(pagination pagination-sm justify-content-center)

app/views/static_pages/search.html.haml
#search.row
  #search_content.col-sm-6.col-lg-4.col-xxl-3
    %h6.mt-3
      Search Query
    = form_tag(search_path, method: :get, class: 'row') do
      .input-group.me-5
        = text_field_tag(:query, params[:query], class: 'form-control form-control-sm custom-placeholder' + input_class, placeholder: "Search")
        = button_tag nil, class: 'btn btn-sm' + search_btn_class do
          %i.bi.bi-search
      %small.mt-2
        = "Showing #{@start_result} - #{@end_result} of #{@items.total_entries} results"
      %h6.mt-3
        Limit Result Type
      .ms-1
        - SiteSearch.model_list.each do |item|
          .form-check
            = check_box_tag "item_types[]", item, params[:item_types]&.include?(item), class: "form-check-input", id: "item_types_#{item}"
            = label_tag "item_types_#{item}", item.titleize, class: "form-check-label"
      - if current_user
        %h6.mt-3
          Filters
        .ms-1
          .form-check
            = check_box_tag :my_owned, '1', params[:my_owned].present?, class: "form-check-input", id: "my_owned"
            = label_tag :my_owned, "Owned Items", class: "form-check-label"
          .form-check
            = check_box_tag :my_items, '1', params[:my_items].present?, class: "form-check-input", id: "my_items"
            = label_tag :my_items, "My Items", class: "form-check-label"
          .form-check
            = check_box_tag :my_stars, '1', params[:my_stars].present?, class: "form-check-input", id: "my_stars"
            = label_tag :my_stars, "My Stars", class: "form-check-label"
      %h6.mt-3
        Tags
      .ms-1.mt-1.mb-5
        - @tags.each do |tag|
          = link_to tag.name, tag, class: 'btn btn-sm btn-primary me-1 mb-1' + link_class
  #search_content.col-sm-6.col-lg-8.col-xxl-9
    .row.grid
      - @items.each do |item|
        .col-sm-12.col-lg-6.col-xxl-4.mb-4
          = render item.card_template_path, item: item
  = will_paginate @items, list_classes: %w(pagination pagination-sm justify-content-center)

app/views/static_pages/user_management.html.haml
- provide(:title, 'User Management')
.container-xxl.g-0
  %h1 User Management
  .mb-4.mt-4
    = link_to 'New User', new_user_path, class: 'btn btn-primary btn-sm'
  %div{"data-controller" => "toggle-admin-only-view"}
    .mb-3
      = form_tag(user_management_path, method: :get, class: 'row') do
        .input-group.mb-2.mt-2
          = text_field_tag(:search, params[:search], class: 'form-control form-control-sm custom-placeholder' + input_class, style: "max-width:250px;", placeholder: "Search by Email or Username")
          = hidden_field_tag :view_admins, "0", data: { "toggle-admin-only-view-target": "admins" }
          = button_tag nil, class: 'btn btn-primary btn-sm' do
            %i.bi.bi-search
            Search
          = link_to 'Clear', user_management_path, class: 'btn btn-secondary btn-sm'
    .form-check.form-switch.ms-2
      = form_tag(user_management_path, method: :get, data: { "toggle-admin-only-view-target": "submit" }) do
        = hidden_field_tag :search, "", data: { "toggle-admin-only-view-target": "query" }
        = check_box_tag :view_admins, 1, false, data: { "action": "click->toggle-admin-only-view#toggle", "toggle-admin-only-view-target": "toggle" }, "class": "form-check-input", "type": "checkbox", "role": "switch"
        %label.form-check-label{:for => "view_admins"} Admin users
      %br/
    - @users.each do |user|
      .mb-3
        = render 'users/user', user: user
    = will_paginate @users, list_classes: %w(pagination pagination-sm justify-content-center)