config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "static_pages#home"
  get '/404', to: 'errors#not_found'
  get  "/about", to: "static_pages#about"
  get  "/help", to: "static_pages#help"
  get  "/user-management", to: "static_pages#user_management"
  get  "/search", to: "static_pages#search"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  devise_scope :user do
    delete "delete_avatar" => "registrations"
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :site_settings, only: [:edit, :update], :path => "settings" do
    member do
      delete :delete_default_avatar
      delete :delete_logo
      delete :delete_favicon
      delete :delete_apple_touch_icon
    end
  end
  resources :help_sections, only: [:new, :create, :edit, :update, :destroy], :path => "documentation"
  resources :support_issues, only: [:index, :show, :new, :create, :update], :path => "support" do
    resources :support_replies, only: [:create], :path => "reply"
    resources :support_comments, only: [:create], :path => "comment"
    resources :support_notes, only: [:create], :path => "note"
  end
  resources :chats, only: [:create, :index] do
    resources :messages, only: [:create]
    collection do
      post :update_index
      get '/join_user_chat/:user_id/', to: 'chats#join_user_chat', :as => :join_user_chat
      get '/join_group_chat/:group_id/', to: 'chats#join_group_chat', :as => :join_group_chat
      get :search
    end
    member do
      post :update_show
      post :pin
      post :unpin
      post :hide
      post :clear_unread_messages
      post :load_more_messages
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :tables, only: [:show, :create, :update]
  get '/edit_collaborations/:record_id/:record_type', to: 'collaborations#edit_collaborations', :as => :edit_collaborations
  get '/:type/:record_id/collaboration_logs', type: /(calendars|decks|notes)/, to: 'collaborations#collaboration_logs', :as => :collaboration_logs
  patch '/change_owner/:record_id/:record_type', to: 'collaborations#change_owner', :as => :change_owner
  patch '/add_collaborator/:record_id/:record_type', to: 'collaborations#add_collaborator', :as => :add_collaborator
  patch '/remove_collaborator/:record_id/:record_type', to: 'collaborations#remove_collaborator', :as => :remove_collaborator
  patch '/add_group/:record_id/:record_type', to: 'collaborations#add_group', :as => :add_group
  patch '/remove_group/:record_id/:record_type', to: 'collaborations#remove_group', :as => :remove_group
  resources :tags, only: [:show] do
    collection do
      get '/edit_item_list/:record_id/:record_type', to: 'tags#edit_item_list', :as => :edit_item_list
      patch '/add/:record_id/:record_type', to: 'tags#add', :as => :add
      patch '/remove/:record_id/:record_type', to: 'tags#remove', :as => :remove
      get '/get_id/:tag_name', to: 'tags#get_id', :as => :get_id
      get :search
    end
  end
  resources :stars, only: []  do
    collection do
      patch '/add/:record_id/:record_type', to: 'stars#add', :as => :add
      patch '/remove/:record_id/:record_type', to: 'stars#remove', :as => :remove
    end
  end
  get '/:type/:record_id/stargazers', type: /(calendars|decks|notes)/, to: 'stars#stargazers', :as => :stargazers
  resources :calendars do
    resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :recurring_events, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :recurring_events do
      patch :add_exception
    end
    get :by_day
    post :update_events_for_tz
  end
  get '/calendar', to: 'calendars#user_calendar', :as => :user_calendar
  get '/calendar/by_day', to: 'calendars#user_calendar_by_day', :as => :user_calendar_by_day
  resources :decks do
    resources :cards do
      patch '/update_position/:display_position', to: 'cards#update_position', :as => :update_position
    end
    post :shuffle
  end
  resources :notes
  resources :groups do
    collection do
      get '/get_id/:group_name', to: 'groups#get_id', :as => :get_id
      get :search
    end
    patch :change_owner
    patch :add_member
    patch :remove_member
    get :edit_members
    get :show_members, :path => "members"
    get ':type', type: /(calendars|decks|notes)/, action: 'show_items', :as => :show_items
    get :membership_logs
    delete :delete_avatar
  end
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    collection do
      get '/get_id/:username', to: 'users#get_id', :as => :get_id
      get :search
    end
    member do
      delete :delete_avatar
      resources :support_issues, only: [:index], :path => "support"
      get :following
      get :followers
      get :show_groups, :path => "groups"
      get :show_stars, :path => "stars"
      get ':type', type: /(calendars|decks|notes)/, action: 'show_items', :as => :show_items
      get :bulk_edit_ownership
      post :bulk_transfer_ownership
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, except: %i[ index new create get_id search ]
  before_action :has_edit_privileges, only: %i[ edit update add_member remove_member edit_members delete_avatar membership_logs ]
  before_action :has_owner_privileges, only: %i[ change_owner destroy ]

  def index
    if params[:view_my_groups].present? && params[:view_my_groups] == '1'
      @groups = Group.search(params[:search], member_to_filter: current_user, page: params[:page], per_page: 5)
    else
      @groups = Group.search(params[:search], page: params[:page], per_page: 5)
    end
  end

  def show
  end

  def show_members
    @members = @group.all_group_members.paginate(page: params[:page], per_page: 5)
  end

  def show_items
    @title = @group.name + ": " + params[:type].capitalize
    @items = SiteSearch.search(
        page: params[:page],
        per_page: 12,
        admin: current_user.admin?,
        user_id: current_user.id,
        item_types: [params[:type]],
        group_id: @group.id
      )
    @tags = @items.select { |item| item.respond_to?(:tags) && item.tags.present? }
      .flat_map(&:tags)
      .uniq
      .sort_by(&:last_activity_at)
      .reverse
  end

  def membership_logs
    @logs = @group.group_member_logs.for_display.paginate(page: params[:page], per_page: 12)
    respond_to do |format|
      format.html
      format.csv { send_data @group.membership_logs_to_csv, filename: "#{@group.name.parameterize.underscore}_membership_logs-#{Time.now.utc.to_formatted_s(:number)}.csv" }
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group),
                                  notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group),
                                  notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url,
                                notice: 'Group was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def edit_members
  end

  def change_owner
    username = group_params[:username]
    username = username[1..-1] if username.slice(0) == '@'
    new_owner = User.find_by(username: username)
    respond_to do |format|
      if new_owner == @group.user
        @alert = 'User is already owner.'
        @members = @group.all_group_members.paginate(page: params[:page], per_page: 5)
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.turbo_stream { render :change_owner_form_update,
                          notice: 'User is already owner.' }
      elsif new_owner
        @group.change_owner(new_owner, current_user)
        @notice = 'Owner was successfully updated.'
        @members = @group.all_group_members.paginate(page: params[:page], per_page: 5)
        format.html { redirect_to group_url(@group),
                          notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
        format.turbo_stream { render :change_owner_form_update }
      else
        @alert = 'Username does not exist.'
        @members = @group.all_group_members.paginate(page: params[:page], per_page: 5)
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.turbo_stream { render :change_owner_form_update,
                          notice: 'Username does not exist.' }
      end
    end
  end

  def add_member
    username = group_params[:username]
    username = username[1..-1] if username.slice(0) == '@'
    respond_to do |format|
      if User.find_by(username: username)
        if @group.members.include?(User.find_by(username: username))
          @notice = 'User is already a member.'
          @members = @group.all_group_members.paginate(page: params[:page], per_page: 5)
          format.html { redirect_to group_url(@group),
                            notice: 'User is already a member.' }
          format.json { render :show, status: :ok, location: @group }
          format.turbo_stream { render :form_update_for_members }
        else
          @group.add_member(User.find_by(username: username), current_user)
          @notice = 'Member was successfully added.'
          @members = @group.all_group_members.paginate(page: params[:page], per_page: 5)
          format.html { redirect_to group_url(@group),
                            notice: 'Member was successfully added.' }
          format.json { render :show, status: :ok, location: @group }
          format.turbo_stream { render :form_update_for_members }
        end
      else
        @alert = 'Username does not exist.'
        @members = @group.all_group_members.paginate(page: params[:page], per_page: 5)
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.turbo_stream { render :form_update_for_members,
                          notice: 'Username does not exist.' }
      end
    end
  end

  def remove_member
    user = User.find(group_params[:user_id])
    @group.remove_member(user, current_user)
    @members = @group.all_group_members.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html { redirect_to group_path(@group),
                                notice: 'User was successfully removed.' }
      format.json { head :no_content }
      format.turbo_stream { render :form_update_for_members }
    end
  end

  def delete_avatar
    @group.avatar.purge if @group.avatar.attached?
    respond_to do |format|
      format.html { redirect_to edit_group_path(@group) }
      format.turbo_stream
    end
  end

  def get_id
    group_name = params[:group_name]
    id = Group.find_by(name: group_name)&.id
    if id
      render json: { id: id }
    else
      render json: { id: 0 }
    end
  end

  def search
    query = params[:query]
    if query.present?
      groups = Group.name_search(query, page: params[:page], per_page: 10)&.pluck(:name)
      render json: groups
    else
      render json: []
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_group
      if params[:id].present?
        @group = Group.find_by(name: params[:id])
      else
        @group = Group.find_by(name: params[:group_id])
      end
      render 'errors/not_found' unless @group
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :username, :description, :avatar, :user_id, :whodunnit,
        group_members_attributes: [:id, :group_id, :user_id, :_destroy]
      )
    end

    def has_edit_privileges
      redirect_to groups_path, alert: 'Not authorized.' unless @group.has_edit_privileges current_user
    end

    def has_owner_privileges
      redirect_to groups_path, alert: 'Not authorized.' unless @group.has_owner_privileges current_user
    end
end

app/views/groups/_activity_log.html.haml
- logs = current_user.viewable_group_activity_logs_for(@group)
- if logs.any?
  %h6 Recent Member Activity
- else
  %h6 No Recent Member Activity
%ul.list-group.list-group-flush
  - logs.each do |log|
    %li{:class => "list-group-item #{list_group_item_log_class}"}
      = log.action_string
      - if log.record.class.to_s == 'User'
        = link_to log.record.handle, user_url(log.record)
      - elsif log.record.class.to_s == 'Event'
        - log.record.all_day ? date = log.record.start : date = log.record.start.in_time_zone(current_timezone(current_user))
        - if current_user || log.record.all_day?
          = link_to log.record.class.to_s.titlecase, calendar_by_day_path(log.record.parent, year: date.year, month: date.month, day: date.day, anchor: log.record.class.to_s + "_" + log.record.id.to_s)
        - else
          %span{"data-controller" => "update-link-data-params-with-local-time", "data-update-link-data-params-with-local-time-datetime" => date}
            = link_to log.record.class.to_s.titlecase, calendar_by_day_path(log.record.parent, year: date.year, month: date.month, day: date.day, anchor: log.record.class.to_s + "_" + log.record.id.to_s), "data-update-link-data-params-with-local-time-target": "link"
      - elsif log.record.class.to_s == 'RecurringEvent'
        - log.record.all_day ? date = log.record.first_event_start : date = log.record.first_event_start.in_time_zone(current_timezone(current_user))
        - if current_user || log.record.all_day?
          = link_to log.record.class.to_s.titlecase, calendar_by_day_path(log.record.parent, year: date.year, month: date.month, day: date.day, anchor: log.record.class.to_s + "_" + log.record.id.to_s)
        - else
          %span{"data-controller" => "update-link-data-params-with-local-time", "data-update-link-data-params-with-local-time-datetime" => date}
            = link_to log.record.class.to_s.titlecase, calendar_by_day_path(log.record.parent, year: date.year, month: date.month, day: date.day, anchor: log.record.class.to_s + "_" + log.record.id.to_s), "data-update-link-data-params-with-local-time-target": "link"
      - elsif log.record.methods.include? :parent
        = link_to log.record.class.to_s.titlecase, send("#{log.record.member_route_type}_path", log.record.parent, log.record)
      - else
        = link_to log.record.class.to_s.titlecase, send("#{log.record.member_route_type}_path", log.record)
      - if log.action_string.include?('tag')
        = log.details
      on #{pretty_time(log.created_at)}

app/views/groups/_avatar_display.html.haml
- if @group.avatar.attached?
  = image_tag(@group.avatar.variant(:thumb))
  %br/
  %br/
  = link_to 'Remove avatar', group_delete_avatar_path(@group), class: link_class, data: { "turbo-method": :delete, turbo_confirm: 'Are you sure?' }
  or set a new one:
= " - Not set" if @group.avatar.attached?
%br/

app/views/groups/_edit_members_form.html.haml
- if @group.has_edit_privileges(current_user)
  .form-label.mb-2 Group Members
  - if (@group and @group.members.count > 0)
    .mb-2.clearfix
      - @group.members.each do |member|
        .float-start.mb-1.me-1
          = form_with model: @group, url: group_remove_member_path(@group), method: "patch" do |form|
            = form.hidden_field :user_id, value: member.id
            = form.button nil, class: "btn btn-sm btn-danger" do
              = member.handle
              %i.bi.bi-x-lg
  = form_with model: @group, url: group_add_member_path(@group), method: "patch" do |form|
    .input-group.mb-5{ "data-controller" => "autocomplete", "data-autocomplete-query-type" => "users" }
      = form.text_field :username, class: "form-control form-control-sm dropdown-toggle group-member custom-placeholder" + input_class, "data-autocomplete-target" => "input", autocomplete: "off", "data-bs-toggle" => "dropdown"
      %ul.w-75.dropdown-menu{"data-autocomplete-target" => "results", :class => "#{dropdown_class}"}
      = form.submit "Add Member", class: "btn btn-primary btn-sm", "data-autocomplete-target": "btn"

app/views/groups/_edit_owner_form.html.haml
- if @group.has_owner_privileges(current_user)
  = form_with model: @group, url: group_change_owner_path(@group), method: "patch" do |form|
    .form-label.mb-2 Owner
    .input-group.mb-5{ "data-controller" => "autocomplete", "data-autocomplete-query-type" => "users" }
      = form.text_field :username, class: "form-control form-control-sm dropdown-toggle custom-placeholder group-owner" + input_class, value: @group.owner.handle, "data-autocomplete-target" => "input", autocomplete: "off", "data-bs-toggle" => "dropdown"
      %ul.w-75.dropdown-menu{"data-autocomplete-target" => "results", :class => "#{dropdown_class}"}
      = form.submit "Change Owner", onclick: "return confirm('Are you sure? You may lose access if you change the owner to another user.')", class: "btn btn-primary btn-sm", "data-autocomplete-target": "btn"
      %div{:class => "form-text#{light_text_class}"} You may lose access if you change the owner to another user.
- elsif @group.has_edit_privileges(current_user)
  .mb-5
    %form
      %fieldset{:disabled => "disabled"}
        %label.form-label Owner
        %input{:class => "form-control form-control-sm#{input_class}", :type => "text", :value => "#{@group.owner_handle}"}/

app/views/groups/_join_chat_form.html.haml
- if current_user and SiteSetting.chat? and @group.member?(current_user) && action_name != 'edit'
  %div{:id => "join_chat_for_#{@group.id}"}
    = link_to join_group_chat_chats_url(@group.id), class: outline_button_class + "btn btn-sm mt-2", data: { turbo_frame: 'offcanvas' } do
      %i.bi.bi-chat-dots-fill
      Join Chat

app/views/groups/_member_index.html.haml
#group-members-index-list
  - members.each do |member|
    .mb-3
      = render member
  = will_paginate members, list_classes: %w(pagination pagination-sm justify-content-center), :params => { :controller => 'groups', :action => 'show_members' }

app/views/groups/_members.html.haml
%a{:class => "me-1 #{link_class}", :href => "#{group_show_members_path(@group)}"}
  %strong.stat{:id => "members_#{@group.id}"}
    = @group.members_count
  - if @group.members_count == 1
    member
  - else
    members
= render 'groups/join_chat_form'
- if @group.all_group_members.any?
  .mt-3.clearfix
    - @group.all_group_members.each do |member|
      - if member.avatar.attached?
        = link_to(image_tag(member.avatar.variant(:tiny)), user_path(member), class: "float-start me-1")
      - elsif SiteSetting.default_avatar.attached?
        = link_to(image_tag(default_avatar_path(:tiny)), user_path(member), class: "float-start me-1")

app/views/groups/change_owner_form_update.turbo_stream.haml
= turbo_stream.update "remote_modal_body" do
  = render "controller_alerts"
  = render "flash_alerts"
  = render "edit_owner_form", group: @group
  = render "edit_members_form", group: @group
  = debug(params) if Rails.env.development?
= turbo_stream.update "group-member-stats-list" do
  = render 'groups/members', group: @group
= turbo_stream.update "group-members-index-list" do
  = render 'groups/member_index', members: @members
= turbo_stream.update "group-member-edit-btns" do
  = render 'groups/edit_group_buttons', group: @group

app/views/groups/delete_avatar.turbo_stream.haml
= turbo_stream.update "avatar_display" do
  = render partial: "avatar_display"
= turbo_stream.update "avatar_and_name" do
  = render partial: "avatar_and_name"

app/views/groups/edit.html.haml
- provide(:title, 'Edit Group')
.container-xxl.g-0
  %span#edit-notice
    = turbo_stream_from @group, "edit_notice"
  %h1 Edit Group
  .row
    .col-sm-6.col-md-4.col-lg-3.col-xl-3.col-xxl-2.mt-3.mb-5
      = render 'groups/avatar_and_name'
      #group-member-stats-list
        = render 'groups/members'
    .col-sm-6.col-md-8.col-lg-9.col-xl-9.col-xxl-10
      = render "form", group: @group
      %br/
      - if @group.has_owner_privileges(current_user)
        .mb-3
          = button_to "Delete Group", @group, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }}, class: "btn btn-danger btn-sm"
      .mb-3
        = link_to "Show group", @group, class: link_class

app/views/groups/edit_members.html.haml
= render "remote_modal", title: "Edit members" do
  = render "edit_owner_form", group: @group
  = render "edit_members_form", group: @group

app/views/groups/form_update_for_members.turbo_stream.haml
= turbo_stream.update "remote_modal_body" do
  = render "edit_owner_form", group: @group
  = render "controller_alerts"
  = render "flash_alerts"
  = render "edit_members_form", group: @group
  = debug(params) if Rails.env.development?
= turbo_stream.update "group-member-stats-list" do
  = render 'groups/members', group: @group
= turbo_stream.update "group-members-index-list" do
  = render 'groups/member_index', members: @members
= turbo_stream.update "group-member-edit-btns" do
  = render 'groups/edit_group_buttons', group: @group

app/views/groups/new.html.haml
- provide(:title, 'New Group')
.container-xxl.g-0
  %h1 New Group
  = render "form", group: @group
  %br/

app/views/groups/show.html.haml
- provide(:title, @group.name)
.container-xxl.g-0
  = render @group
  %br/