config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "static_pages#home"
  get '/404', to: 'errors#not_found'
  get  "/about", to: "static_pages#about"
  get  "/help", to: "static_pages#help"
  get  "/user-management", to: "static_pages#user_management"
  get  "/search", to: "static_pages#search"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  devise_scope :user do
    delete "delete_avatar" => "registrations"
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :site_settings, only: [:edit, :update], :path => "settings" do
    member do
      delete :delete_default_avatar
      delete :delete_logo
      delete :delete_favicon
      delete :delete_apple_touch_icon
    end
  end
  resources :help_sections, only: [:new, :create, :edit, :update, :destroy], :path => "documentation"
  resources :support_issues, only: [:index, :show, :new, :create, :update], :path => "support" do
    resources :support_replies, only: [:create], :path => "reply"
    resources :support_comments, only: [:create], :path => "comment"
    resources :support_notes, only: [:create], :path => "note"
  end
  resources :chats, only: [:create, :index] do
    resources :messages, only: [:create]
    collection do
      post :update_index
      get '/join_user_chat/:user_id/', to: 'chats#join_user_chat', :as => :join_user_chat
      get '/join_group_chat/:group_id/', to: 'chats#join_group_chat', :as => :join_group_chat
      get :search
    end
    member do
      post :update_show
      post :pin
      post :unpin
      post :hide
      post :clear_unread_messages
      post :load_more_messages
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :tables, only: [:show, :create, :update]
  get '/edit_collaborations/:record_id/:record_type', to: 'collaborations#edit_collaborations', :as => :edit_collaborations
  get '/:type/:record_id/collaboration_logs', type: /(calendars|decks|notes)/, to: 'collaborations#collaboration_logs', :as => :collaboration_logs
  patch '/change_owner/:record_id/:record_type', to: 'collaborations#change_owner', :as => :change_owner
  patch '/add_collaborator/:record_id/:record_type', to: 'collaborations#add_collaborator', :as => :add_collaborator
  patch '/remove_collaborator/:record_id/:record_type', to: 'collaborations#remove_collaborator', :as => :remove_collaborator
  patch '/add_group/:record_id/:record_type', to: 'collaborations#add_group', :as => :add_group
  patch '/remove_group/:record_id/:record_type', to: 'collaborations#remove_group', :as => :remove_group
  resources :tags, only: [:show] do
    collection do
      get '/edit_item_list/:record_id/:record_type', to: 'tags#edit_item_list', :as => :edit_item_list
      patch '/add/:record_id/:record_type', to: 'tags#add', :as => :add
      patch '/remove/:record_id/:record_type', to: 'tags#remove', :as => :remove
      get '/get_id/:tag_name', to: 'tags#get_id', :as => :get_id
      get :search
    end
  end
  resources :stars, only: []  do
    collection do
      patch '/add/:record_id/:record_type', to: 'stars#add', :as => :add
      patch '/remove/:record_id/:record_type', to: 'stars#remove', :as => :remove
    end
  end
  get '/:type/:record_id/stargazers', type: /(calendars|decks|notes)/, to: 'stars#stargazers', :as => :stargazers
  resources :calendars do
    resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :recurring_events, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :recurring_events do
      patch :add_exception
    end
    get :by_day
    post :update_events_for_tz
  end
  get '/calendar', to: 'calendars#user_calendar', :as => :user_calendar
  get '/calendar/by_day', to: 'calendars#user_calendar_by_day', :as => :user_calendar_by_day
  resources :decks do
    resources :cards do
      patch '/update_position/:display_position', to: 'cards#update_position', :as => :update_position
    end
    post :shuffle
  end
  resources :notes
  resources :groups do
    collection do
      get '/get_id/:group_name', to: 'groups#get_id', :as => :get_id
      get :search
    end
    patch :change_owner
    patch :add_member
    patch :remove_member
    get :edit_members
    get :show_members, :path => "members"
    get ':type', type: /(calendars|decks|notes)/, action: 'show_items', :as => :show_items
    get :membership_logs
    delete :delete_avatar
  end
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    collection do
      get '/get_id/:username', to: 'users#get_id', :as => :get_id
      get :search
    end
    member do
      delete :delete_avatar
      resources :support_issues, only: [:index], :path => "support"
      get :following
      get :followers
      get :show_groups, :path => "groups"
      get :show_stars, :path => "stars"
      get ':type', type: /(calendars|decks|notes)/, action: 'show_items', :as => :show_items
      get :bulk_edit_ownership
      post :bulk_transfer_ownership
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  include Searchable

  has_many :taggings, dependent: :destroy

  before_save :update_last_activity_at

  UserItems.item_list.each do |item|
    has_many "#{item}".to_sym, :through => :taggings, source: :record, source_type: "#{UserItems.class(item)}"
  end

  VALID_TAG_REGEX = /\A[a-z\d\-_+]*\z/i
  validates :name, presence: true, length: { maximum: 100 },
                    format: { with: VALID_TAG_REGEX, message: 'can only contain letters, numbers, dashes, underscores, or pluses' },
                    uniqueness: { case_sensitive: false }

  default_scope { order(updated_at: :desc) }
  scope :ordered_by_id, -> { reorder(id: :asc) }

  settings do
    mappings dynamic: false do
      indexes :name, type: :text
    end
  end

  def as_indexed_json(options = {})
    as_json(only: [:name])
  end

  def to_param
    self.name_was
  end

  def self.search(query, page: 1, per_page: 50)
    return unless query.present?

    page = page.to_i <= 0 ? 1 : page.to_i

    search_body = {
      query: {
        bool: {
          must: [
            {
              multi_match: {
                query: query,
                fields: ['name'],
                "fuzziness": "AUTO"
              }
            }
          ]
        }
      }
    }

    if per_page
      search_body.merge!({
        from: (page.to_i - 1) * per_page.to_i,
        size: per_page.to_i
      })
    end

    search_response = Tag.__elasticsearch__.search(search_body)

    WillPaginate::Collection.create(page.to_i, per_page.to_i, search_response.response['hits']['total']['value']) do |pager|
      pager.replace(search_response.records.to_a)
    end
  end

  def card_template_path
    "tags/tag_card"
  end

  def should_delete?
    UserItems.item_list.reduce(0) { |sum, item| sum + self.send(item).count } == 0
  end

  def public_items
    UserItems.item_list.map { |item| self.send(item).public_items }.flatten.uniq.sort_by(&:updated_at).reverse
  end

  def self.public_tags
    UserItems.public_items.map(&:tags).flatten.uniq.sort_by(&:updated_at).reverse
  end

  private

    def update_last_activity_at
      self.last_activity_at = Time.current
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, except: %i[show]
  before_action :set_tag, only: %i[show]
  before_action :set_record, only: %i[edit_item_list add remove]
  before_action :has_edit_privileges, only: %i[edit_item_list add remove]

  # GET /tags/1 or /tags/1.json
  def show
    if @tag
      if current_user
        @items = SiteSearch.search(
          page: params[:page],
          per_page: 12,
          admin: current_user.admin?,
          user_id: current_user.id,
          item_types: [params[:type]],
          tag: @tag.name
        )
      else
        @items = SiteSearch.search(
          page: params[:page],
          per_page: 12,
          item_types: [params[:type]],
          tag: @tag.name
        )
      end
    else
      @items = []
    end
  end

  def edit_item_list
    @tag = Tag.new
  end

  def add
    # if tag name exists
    if Tag.where(name: tag_params[:tag_name]).first
      @tag = Tag.where(name: tag_params[:tag_name]).first
      if @record.tag?(@tag)
        @tag = Tag.new
        respond_to do |format|
          format.turbo_stream { render :form_update,
                                  locals: {
                                    notice: "Tag already assigned to #{@record.type.downcase}."
                                  } }
          format.html { render @record,
            notice: "Tag already assigned to #{@record.type.downcase}." }
        end
      else
        @record.tag(@tag, current_user)
        @tag = Tag.new
        respond_to do |format|
          format.turbo_stream { render :form_update }
          format.html { render @record,
            notice: 'Tag was successfully added.'}
        end
      end
    # if tag name does not exist
    else
      @tag = Tag.new({ name: tag_params[:tag_name] })
      if @tag.save
        @record.tag(@tag, current_user)
        @tag = Tag.new
        respond_to do |format|
          format.turbo_stream { render :form_update }
          format.html { render @record }
        end
      else
        respond_to do |format|
          format.turbo_stream { render :form_update,
                                       status: :unprocessable_entity }
          format.html { render @record, status: :unprocessable_entity }
        end
      end
    end
  end

  def remove
    @tag = Tag.find(tag_params[:tag_id])
    @record.untag(@tag, current_user)
    @tag.destroy if @tag.should_delete?
    @tag = Tag.new
    respond_to do |format|
      format.turbo_stream { render :form_update }
      format.html { render @record }
    end
  end

  def get_id
    tag_name = params[:tag_name]
    id = Tag.find_by(name: tag_name)&.id
    if id
      render json: { id: id }
    else
      render json: { id: 0 }
    end
  end

  def search
    query = params[:query]
    if query.present?
      tags = Tag.search(query, page: params[:page], per_page: 10)&.pluck(:name)
      render json: tags
    else
      render json: []
    end
  end

  private

    def set_tag
      @tag = Tag.find_by(name: params[:id])
      @tag_name = @tag&.name || params[:id]
    end

    def set_record
      @record ||= params[:record_type].capitalize.constantize.find(params[:record_id])
    end

    def tag_params
      params.require(:tag).permit(:tag_id, :tag_name)
    end

    def has_edit_privileges
      redirect_to root_path, alert: 'Not authorized.' unless @record.has_edit_privileges current_user
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
.form-label.mb-2 Tags
- if (record and record.tags_count > 0)
  .mb-2.clearfix
    - record.tags.each do |tag|
      .float-start.mb-1.me-1
        = form_with model: @tag, url: remove_tags_path(record.id, record.type), method: "patch" do |form|
          = form.hidden_field :tag_id, value: tag.id
          = form.button nil, class: "btn btn-sm btn-danger" do
            = tag.name
            %i.bi.bi-x-lg
= form_with model: @tag, url: add_tags_path(record.id, record.type), method: "patch" do |form|
  = render 'error_messages', object: tag, object_name: 'this tag'
  .input-group{ "data-controller" => "autocomplete", "data-autocomplete-query-type" => "tags" }
    = form.text_field :tag_name, class: "form-control form-control-sm dropdown-toggle custom-placeholder" + input_class, "data-autocomplete-target" => "input", autocomplete: "off", "data-bs-toggle" => "dropdown"
    %ul.w-75.dropdown-menu{"data-autocomplete-target" => "results", :class => "#{dropdown_class}"}
    = form.submit "Add Tag", class: "btn btn-primary btn-sm", "data-autocomplete-target": "btn"
  %div{:class => "form-text mb-3 #{light_text_class}"} Only letters, numbers, dashes, underscores, and pluses.

app/views/tags/_item_edit_tags_form.html.haml
%div{"data-controller" => "remove-nested-form-item"}
  .float-start.mb-1.me-1
    = fields_for "#{record.type.downcase}[taggings_attributes][#{tagging.persisted? ? tagging.id : Time.now.to_i }]", tagging do |ff|
      = button_tag type: "button", class: "btn btn-sm btn-danger", data: { action: "remove-nested-form-item#removeItem" } do
        = tagging.tag.name
        %i.bi.bi-x-lg
      = ff.hidden_field :tag_name
      = ff.hidden_field :id
      = ff.hidden_field :tag_id
      = ff.hidden_field :_destroy

app/views/tags/_item_form.html.haml
#item_tags_notice
.form-label.mb-2 Tags
#item_tags.mb-2.clearfix
  - record.taggings.order_tag_name.each do |tagging|
    = render "tags/item_edit_tags_form", record: record, tagging: tagging
.input-group.mb-3{"data-add-nested-form-item-record-type" => "#{record.type}", "data-controller" => "add-nested-form-item autocomplete", "data-autocomplete-query-type" => "tags"}
  = text_field_tag(:tag_name, nil, class: "form-control form-control-sm dropdown-toggle" + input_class, "data-autocomplete-target" => "input", autocomplete: "off", "data-bs-toggle" => "dropdown")
  %ul.w-75.dropdown-menu{"data-autocomplete-target" => "results", :class => "#{dropdown_class}"}
  = button_tag type: "button", class: "btn btn-primary btn-sm", data: { action: "add-nested-form-item#addTag", "autocomplete-target": "btn" } do
    %i.bi.bi-plus
    Add Tag

app/views/tags/_item_tags_list.html.haml
- record.tags.sort_by(&:name).each do |tag|
  = link_to tag.name, tag, class: 'tag-list-item me-1' + link_class
- if record.has_edit_privileges(current_user) and record.tags.count == 0
  = link_to edit_item_list_tags_path(record_id: record.id, record_type: record.type), class: link_class, data: { turbo_frame: 'remote_modal' } do
    %i.bi.bi-tag-fill<>
    Add Tags

- elsif record.has_edit_privileges(current_user)
  = link_to edit_item_list_tags_path(record_id: record.id, record_type: record.type), class: link_class, data: { turbo_frame: 'remote_modal' } do
    %i.bi.bi-tag-fill<>
    Edit tags

app/views/tags/edit_item_list.html.haml
= render "remote_modal", title: @record.type + " Tags" do
  = render "form", tag: @tag, record: @record

app/views/tags/form_update.turbo_stream.haml
= turbo_stream.update "remote_modal_body" do
  - if notice
    .alert.alert-primary.alert-dismissible{:role => "alert"}
      %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}
      = notice
  = render "form", tag: @tag, record: @record
  = debug(params) if Rails.env.development?
= turbo_stream.update "tags-list" do
  = render 'item_tags_list', record: @record

app/views/tags/show.html.haml
- provide(:title, 'Tag: ' + @tag_name)
%h1
  %i.bi.bi-tag-fill>
  Tag: #{@tag_name}
#tags_content.row.grid
  - @items.each do |item|
    .col-sm-6.col-lg-4.col-xxl-3.mb-4.grid-item
      = render item.card_template_path, item: item
- if @items.present?
  = will_paginate @items, list_classes: %w(pagination pagination-sm justify-content-center)