config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "static_pages#home"
  get '/404', to: 'errors#not_found'
  get  "/about", to: "static_pages#about"
  get  "/help", to: "static_pages#help"
  get  "/user-management", to: "static_pages#user_management"
  get  "/search", to: "static_pages#search"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  devise_scope :user do
    delete "delete_avatar" => "registrations"
  end
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :site_settings, only: [:edit, :update], :path => "settings" do
    member do
      delete :delete_default_avatar
      delete :delete_logo
      delete :delete_favicon
      delete :delete_apple_touch_icon
    end
  end
  resources :help_sections, only: [:new, :create, :edit, :update, :destroy], :path => "documentation"
  resources :support_issues, only: [:index, :show, :new, :create, :update], :path => "support" do
    resources :support_replies, only: [:create], :path => "reply"
    resources :support_comments, only: [:create], :path => "comment"
    resources :support_notes, only: [:create], :path => "note"
  end
  resources :chats, only: [:create, :index] do
    resources :messages, only: [:create]
    collection do
      post :update_index
      get '/join_user_chat/:user_id/', to: 'chats#join_user_chat', :as => :join_user_chat
      get '/join_group_chat/:group_id/', to: 'chats#join_group_chat', :as => :join_group_chat
      get :search
    end
    member do
      post :update_show
      post :pin
      post :unpin
      post :hide
      post :clear_unread_messages
      post :load_more_messages
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :tables, only: [:show, :create, :update]
  get '/edit_collaborations/:record_id/:record_type', to: 'collaborations#edit_collaborations', :as => :edit_collaborations
  get '/:type/:record_id/collaboration_logs', type: /(calendars|decks|notes)/, to: 'collaborations#collaboration_logs', :as => :collaboration_logs
  patch '/change_owner/:record_id/:record_type', to: 'collaborations#change_owner', :as => :change_owner
  patch '/add_collaborator/:record_id/:record_type', to: 'collaborations#add_collaborator', :as => :add_collaborator
  patch '/remove_collaborator/:record_id/:record_type', to: 'collaborations#remove_collaborator', :as => :remove_collaborator
  patch '/add_group/:record_id/:record_type', to: 'collaborations#add_group', :as => :add_group
  patch '/remove_group/:record_id/:record_type', to: 'collaborations#remove_group', :as => :remove_group
  resources :tags, only: [:show] do
    collection do
      get '/edit_item_list/:record_id/:record_type', to: 'tags#edit_item_list', :as => :edit_item_list
      patch '/add/:record_id/:record_type', to: 'tags#add', :as => :add
      patch '/remove/:record_id/:record_type', to: 'tags#remove', :as => :remove
      get '/get_id/:tag_name', to: 'tags#get_id', :as => :get_id
      get :search
    end
  end
  resources :stars, only: []  do
    collection do
      patch '/add/:record_id/:record_type', to: 'stars#add', :as => :add
      patch '/remove/:record_id/:record_type', to: 'stars#remove', :as => :remove
    end
  end
  get '/:type/:record_id/stargazers', type: /(calendars|decks|notes)/, to: 'stars#stargazers', :as => :stargazers
  resources :calendars do
    resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :recurring_events, only: [:show, :new, :create, :edit, :update, :destroy]
    resources :recurring_events do
      patch :add_exception
    end
    get :by_day
    post :update_events_for_tz
  end
  get '/calendar', to: 'calendars#user_calendar', :as => :user_calendar
  get '/calendar/by_day', to: 'calendars#user_calendar_by_day', :as => :user_calendar_by_day
  resources :decks do
    resources :cards do
      patch '/update_position/:display_position', to: 'cards#update_position', :as => :update_position
    end
    post :shuffle
  end
  resources :notes
  resources :groups do
    collection do
      get '/get_id/:group_name', to: 'groups#get_id', :as => :get_id
      get :search
    end
    patch :change_owner
    patch :add_member
    patch :remove_member
    get :edit_members
    get :show_members, :path => "members"
    get ':type', type: /(calendars|decks|notes)/, action: 'show_items', :as => :show_items
    get :membership_logs
    delete :delete_avatar
  end
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    collection do
      get '/get_id/:username', to: 'users#get_id', :as => :get_id
      get :search
    end
    member do
      delete :delete_avatar
      resources :support_issues, only: [:index], :path => "support"
      get :following
      get :followers
      get :show_groups, :path => "groups"
      get :show_stars, :path => "stars"
      get ':type', type: /(calendars|decks|notes)/, action: 'show_items', :as => :show_items
      get :bulk_edit_ownership
      post :bulk_transfer_ownership
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  include HasRichTextExtensions
  include IsSubitem

  belongs_to :parent, class_name: 'Deck', foreign_key: 'deck_id'
  has_rich_text :front
  has_rich_text :back

  validates_presence_of :front
  validates_presence_of :back

  before_create :set_display_position
  before_destroy :reset_deck_positions

  default_scope { order(:display_position) }

  settings do
    mappings dynamic: false do
      indexes :front, type: :text
      indexes :back, type: :text
      indexes :user_id, type: :integer
      indexes :visibility, type: :integer
      indexes :all_collaborator_ids, type: :integer
    end
  end

  def as_indexed_json(options = {})
    as_json
      .merge(front: front.to_plain_text)
      .merge(back: back.to_plain_text)
      .merge(user_id: parent.user_id)
      .merge(visibility: parent.visibility)
      .merge(all_collaborator_ids: (parent.collaborators.pluck(:id) + parent.group_members.pluck(:id) + parent.group_owners.pluck(:id) + [parent.user_id]).uniq)
  end

  def set_display_position
    self.display_position = self.parent.cards.count
  end

  def reset_deck_positions
    cards = self.parent.cards - [self]
    cards.each_with_index do | card, i |
      card.update(display_position: i)
    end
  end

  def prev_card
    parent.cards.where('display_position < ?', display_position).last
  end

  def next_card
    parent.cards.where('display_position > ?', display_position).first
  end

  def update_display_position(position)
    return unless position.is_a?(Integer)
    return if position == self.display_position

    cards_to_update = self.parent.cards - [self]
    end_index = cards_to_update.length
    position = end_index if position < 0
    position = 0 if position >= self.parent.cards.count

    # Update the current card's position
    self.update(display_position: position)

    # Update the positions of the other cards
    cards_to_update.each_with_index do |card, i|
      # Adjust the position depending on the current position of the card
      new_position = if position == 0
                       i + 1
                     elsif position == end_index
                       i
                     elsif i < position
                       i
                     else
                       i + 1
                     end
      card.update(display_position: new_position)
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_deck
  before_action :set_card, only: %i[show edit update destroy update_position]
  before_action :authenticate_user!, except: %i[index show]
  before_action :has_owner_privileges, only: %i[ destroy ]
  before_action :has_edit_privileges, only: %i[edit update new create destroy update_position]
  before_action :has_view_privileges, only: %i[index show]

  # GET /cards or /cards.json
  def index
    @cards = @deck.cards.all.paginate(page: params[:page], per_page: 12)
    respond_to do |format|
      format.html
      format.csv { send_data @deck.cards_to_csv, filename: "cards-#{Time.now.utc.to_formatted_s(:number)}.csv" }
    end
  end

  # GET /cards/1 or /cards/1.json
  def show; end

  # GET /cards/new
  def new
    @card = @deck.cards.build
  end

  # GET /cards/1/edit
  def edit; end

  # POST /cards or /cards.json
  def create
    @card = @deck.cards.build(card_params)
    respond_to do |format|
      if @card.save && card_params[:create_another] == '1'
        format.html { redirect_to new_deck_card_path,
                                  notice: 'Card was successfully created.' }
        format.json { render :show, status: :created,
                              location: deck_card_url(@card.deck_id, @card) }
      elsif @card.save
        format.html { redirect_to deck_card_url(@card.deck_id, @card),
                  notice: 'Card was successfully created.' }
        format.json { render :show, status: :created,
              location: deck_card_url(@card.deck_id, @card) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1 or /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to deck_card_url(@card.deck_id, @card),
                                  notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok,
                             location: deck_card_url(@card.deck_id, @card) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1 or /cards/1.json
  def destroy
    @card.destroy

    respond_to do |format|
      format.html { redirect_to deck_cards_url,
                                notice: 'Card was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def update_position
    @card.update_display_position(params[:display_position].to_i)
    if params[:pagination] && params[:pagination][:update]
      @cards = @deck.cards.paginate(page: params[:pagination][:page], per_page: 12)
      respond_to do |format|
        format.html { head :no_content }
        format.turbo_stream { render :update_card_display_order }
      end
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find_by_id(params[:deck_id])
      render 'errors/not_found' unless @deck
    end

    def set_card
      @card = @deck.cards.find_by_id(params[:id])
      @card ||= @deck.cards.find_by_id(params[:card_id])
      render 'errors/not_found' unless @card
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:front, :back, :deck_id, :create_another, :whodunnit)
    end

    def has_edit_privileges
      redirect_to decks_path, alert: 'Not authorized.' unless @deck.has_edit_privileges current_user
    end

    def has_view_privileges
      render 'errors/not_found' unless @deck.has_view_privileges(current_user)
    end

    def has_owner_privileges
      redirect_to decks_path, alert: 'Not authorized.' unless @deck.has_owner_privileges current_user
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.haml
%div{:id => "#{dom_id card}"}
  %div{:class => "card notecard #{card_class} mb-4"}
    - if action_name == 'show'
      = render 'cards/flip_card', card: @card
    - else
      = render 'cards/no_flip_card', card: card
    = render 'cards/card_footer', card: card

app/views/cards/_card_card.html.haml
- card ||= item
%div{:id => "#{dom_id card}"}
  %div{:class => "card card-card #{card_class}"}
    .card-header
      .float-end.ms-1
        %i.bi.bi-paperclip
      %span#collaborators-list
        = render 'collaborations/owner', record: card
    .card-body
      .mb-3
        = truncate_actiontext_html(card.front.to_s, link_class: link_class, max_length: 300, read_more_path: deck_card_path(card.parent, card)).html_safe
    .card-footer
      %small
        .mb-2.text-center{"data-turbolinks" => "false"}
          - if card.has_edit_privileges(current_user)
            %strong.me-1<>
              = card.status
          = link_to deck_card_path(card.parent, card), class: "me-1" + link_class do
            %i.bi.bi-card-text<>
            Show card

app/views/cards/_card_footer.html.haml
- if @deck.has_edit_privileges(current_user)
  .card-footer
    %small
      .mb-2.text-center
        %strong.me-1<>= card.status
        = link_to edit_deck_card_path(card.deck_id, card), class: "me-1" + link_class do
          %i.bi.bi-pencil-fill<>
          Edit card
        = link_to new_deck_card_path(card.deck_id), class: "me-1" + link_class do
          %i.bi.bi-plus<>
          Add card

app/views/cards/_cards_list.html.haml
- if @deck.has_edit_privileges(current_user)
  %div{"data-controller" => "sort", "data-sort-parent" => "#{@deck.id}", "data-sort-record-type" => "Card", "data-sort-start-position" => "#{cards&.first&.display_position}"}
    - cards.each do |card|
      = render card
- else
  - cards.each do |card|
    = render card

app/views/cards/_flip_card.html.haml
%div{"data-controller" => "flashcards"}
  #flipcard.card-body{"data-action" => "click->flashcards#flip touchstart->flashcards#startTouch touchmove->flashcards#moveTouch touchend->flashcards#endTouch", "data-flashcards-target" => "card"}
    #front.mb-3.text-center{"data-flashcards-target" => "front"}
      = card.front
    #back.mb-3.text-center{"data-flashcards-target" => "back"}
      = card.back

app/views/cards/_form.html.haml
%div{:class => "card card-deck #{card_class}"}
  .card-body
    = form_for([@deck, @card]) do |form|
      = render 'error_messages', object: @card, object_name: 'this card'
      = form.hidden_field :whodunnit, value: current_user.id
      #tables-data.mb-3{"data-controller" => "rich-text", "data-record-id" => "#{@card.id}", "data-record-type" => "Card"}
        = form.label :front, style: "display: block", class: "form-label"
        = form.rich_text_area :front, class: "form-control" + input_class
      #tables-data.mb-3{"data-controller" => "rich-text", "data-record-id" => "#{@card.id}", "data-record-type" => "Card"}
        = form.label :back, style: "display: block", class: "form-label"
        = form.rich_text_area :back, class: "form-control" + input_class
      - if action_name == 'new'
        .mb-3
          = form.check_box :create_another, class: "form-check-input"
          = form.label :create_another, "Create another", class: "form-check-label"
      .mb-3
        = form.submit "Submit", class: "btn btn-primary btn-sm", id: "edit-btn"

app/views/cards/_no_flip_card.html.haml
%div{:class => "card-body #{sort_class(@deck)}"}
  #front.mb-3.text-center
    = render 'cards/sort_buttons', card: card
    = card.front
  %hr/
  #back.mb-3.text-center
    = card.back

app/views/cards/_shuffle.html.haml
- if @deck.has_edit_privileges(current_user)
  = link_to deck_shuffle_path(@deck), class: "btn btn-primary btn-sm me-2 float-end", data: { turbo_method: "post" } do
    %i.bi.bi-shuffle
    Shuffle

app/views/cards/_sort_buttons.html.haml
- if @deck.has_edit_privileges(current_user)
  = form_with url: deck_card_update_position_path(card.parent, card, card.display_position - 1), method: "patch", class: "move-up" do |form|
    = form.button nil, class: "btn btn-secondary ms-1  btn-sm float-end"  do
      %i.bi.bi-arrow-up
    = hidden_field_tag "pagination[page]", "#{@cards.current_page}"
    = hidden_field_tag "pagination[update]", "1"
  = form_with url: deck_card_update_position_path(card.parent, card, card.display_position + 1), method: "patch", class: "move-down" do |form|
    = form.button nil, class: "btn btn-secondary btn-sm float-end"  do
      %i.bi.bi-arrow-down
    = hidden_field_tag "pagination[page]", "#{@cards.current_page}"
    = hidden_field_tag "pagination[update]", "1"

app/views/cards/edit.html.haml
- provide(:title, 'Edit Card')
.container-xxl.g-0
  .row.justify-content-center
    .col-sm-12.col-md-12.col-lg-10.col-xl-8.col-xxl-8
      %span#edit-notice
        = turbo_stream_from @card, "edit_notice"
      %h1 Edit Card
      = render "form", card: [@deck, @card]
      %br/
      - if @card.has_owner_privileges(current_user)
        .mb-3
          = button_to "Delete Card", deck_card_path(@card.deck_id, @card.id), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' }}, class: "btn btn-danger btn-sm"
      .mb-3
        = link_to "Show card", deck_card_path(@card.deck_id, @card.id), class: link_class

app/views/cards/index.html.haml
- provide(:title, 'Cards')
.container-xxl.g-0
  .row.justify-content-center
    .col-sm-12.col-md-12.col-lg-8.mb-4
      %h1
        Cards
        = link_to deck_cards_path(@deck, format: "csv"), class: "btn btn-primary btn-sm float-end" do
          %i.bi.bi-shuffle
          Export CSV
        = render 'cards/shuffle'
      %span#cards-list
        = render 'cards/cards_list', cards: @cards
  = will_paginate @cards, list_classes: %w(pagination pagination-sm justify-content-center)
  .row.justify-content-center
    .col-sm-12.col-md-12.col-lg-8
      = link_to deck_path(@deck.id), class: link_class do
        %i.bi.bi-card-text>
        Back to deck

app/views/cards/new.html.haml
- provide(:title, 'New Card')
.container-xxl.g-0
  .row.justify-content-center
    .col-sm-12.col-md-12.col-lg-10.col-xl-8.col-xxl-8
      %h1 New Card
      = render "form", card: [@deck, @card]
      %br/
      = link_to deck_path(@deck.id), class: link_class do
        %i.bi.bi-card-text>
        Back to deck

app/views/cards/show.html.haml
- provide(:title, 'Card')
.container-xxl.g-0
  .row
    .col-sm-12.col-md-12.col-lg-1.col-xl-2.col-xxl-2.d-xs-none.d-none.d-lg-block.mt-4.mb-4
      - if !@card.prev_card.nil?
        = link_to deck_card_path(@card.deck_id, @card.prev_card), id: "prev-card" do
          %button.btn.btn-secondary.btn-sm.float-end.btn-prev{:type => "button"}
            %i.bi.bi-caret-left-fill
    .col-sm-12.col-md-12.col-lg-10.col-xl-8.col-xxl-8
      = render @card
      - if !@card.prev_card.nil?
        = link_to deck_card_path(@card.deck_id, @card.prev_card), id: "prev-card" do
          %button.btn.btn-secondary.btn-sm.d-lg-none.d-xl-none.d-xxl-none.mb-4.btn-prev{:type => "button"}
            %i.bi.bi-caret-left-fill
      - if !@card.next_card.nil?
        = link_to deck_card_path(@card.deck_id, @card.next_card), id: "next-card" do
          %button.btn.btn-secondary.btn-sm.float-end.d-lg-none.d-xl-none.d-xxl-none.mb-4.btn-next{:type => "button"}
            %i.bi.bi-caret-right-fill
    .col-sm-12.col-md-12.col-lg-1.col-xl-2.col-xxl-2.d-xs-none.d-none.d-lg-block.mt-4.mb-4
      - if !@card.next_card.nil?
        = link_to deck_card_path(@card.deck_id, @card.next_card), id: "next-card" do
          %button.btn.btn-secondary.btn-sm.btn-next{:type => "button"}
            %i.bi.bi-caret-right-fill
  .row.justify-content-center
    .col-sm-12.col-md-12.col-lg-10.col-xl-8.col-xxl-8
      = link_to deck_path(@deck.id), class: link_class do
        %i.bi.bi-card-text>
        Back to deck

app/views/cards/update_card_display_order.turbo_stream.haml
= turbo_stream.update "cards-list" do
  = render 'cards/cards_list', cards: @cards